package forktex.SoccerManagerBELite.enums;

public enum LogCategoryType {
    LOGIN,
    CREATE_ACCOUNT,

    GET_PROFILE,
    GET_TEAM_INFORMATION,
    GET_TEAM_PLAYERS,
    GET_PLAYERS_ON_MARKET,
    GET_PLAYER_INFORMATION,

    UPDATE_PROFILE,
    UPDATE_TEAM_INFORMATION,
    UPDATE_PLAYER_INFORMATION,

    PLACE_PLAYER_ON_MARKET,
    WITHDRAW_PLAYER_FROM_MARKET,
    BUY_PLAYER_FROM_MARKET,

    TEST,
}
